all:
  hosts:
    localhost:
      ansible_connection: local

pcloud:
  hosts:
    localhost:

portainer:
  hosts:
    localhost:

netbox:
  hosts:
    localhost:

k3s:
  hosts:
    localhost:

yubikey:
  hosts:
    localhost:

fail2ban:
  hosts:
    localhost:
