---
name: Uninstall Fail2ban

'on':
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ansible/playbooks/uninstall_fail2ban.yml'
      - 'ansible/playbooks/roles/fail2ban_uninstall/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Execute playbook
        working-directory: ansible
        env:
          ANSIBLE_DISPLAY_ARGS_TO_STDOUT: 'false'
        run: |
          ansible-playbook playbooks/uninstall_fail2ban.yml \
            -i inventories/production/hosts.yml \
            --become
